# Generated by Django 3.1.2 on 2020-10-07 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Action', max_length=20)),
                ('item_num', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MovieProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(default='Fast Frious', max_length=20)),
                ('movie_describe', models.TextField(max_length=100)),
                ('movie_score', models.FloatField(default=10.0)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=500.0)),
                ('picture', models.ImageField(upload_to=None)),
                ('categorye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieRent.category')),
            ],
        ),
    ]
