# Generated by Django 3.1.1 on 2020-10-13 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieRent', '0002_auto_20201012_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieproducts', to='movieRent.category'),
        ),
        migrations.AlterField(
            model_name='movieproduct',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='movieproduct',
            table='movie',
        ),
    ]
