# Generated by Django 3.1.1 on 2020-10-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRent', '0003_auto_20201013_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieproduct',
            name='movie_describe',
            field=models.TextField(max_length=1000),
        ),
    ]
