# Generated by Django 3.1.1 on 2020-10-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRent', '0004_auto_20201013_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieproduct',
            name='picture',
            field=models.ImageField(null=True, upload_to='movie_pic/'),
        ),
    ]
