# Generated by Django 3.1.1 on 2020-10-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRent', '0005_auto_20201013_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='movieproduct',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/movie_pic/'),
        ),
        migrations.AlterField(
            model_name='movieproduct',
            name='videofile',
            field=models.FileField(null=True, upload_to='static/videos/', verbose_name=''),
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='movieproduct',
            table=None,
        ),
    ]
