# Generated by Django 3.1.1 on 2020-10-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRent', '0007_auto_20201014_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, max_length=200, unique=True),
        ),
    ]
