# Generated by Django 3.1.1 on 2020-10-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRent', '0008_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieproduct',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
